-- Run this in Supabase Dashboard > SQL Editor to enable cloud sync for sales.
CREATE TABLE IF NOT EXISTS public.sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no text NOT NULL UNIQUE,
  customer_id bigint,
  customer_name text NOT NULL,
  subtotal numeric NOT NULL DEFAULT 0,
  gst_percent numeric NOT NULL DEFAULT 0,
  gst_amount numeric NOT NULL DEFAULT 0,
  grand_total numeric NOT NULL DEFAULT 0,
  payment_mode text NOT NULL DEFAULT 'Cash',
  created_at timestamptz NOT NULL DEFAULT now(),
  lines jsonb NOT NULL DEFAULT '[]'::jsonb
);

ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon sales read" ON public.sales;
CREATE POLICY "Allow anon sales read" ON public.sales FOR SELECT TO anon USING (true);
DROP POLICY IF EXISTS "Allow anon sales insert" ON public.sales;
CREATE POLICY "Allow anon sales insert" ON public.sales FOR INSERT TO anon WITH CHECK (true);
DROP POLICY IF EXISTS "Allow anon sales update" ON public.sales;
CREATE POLICY "Allow anon sales update" ON public.sales FOR UPDATE TO anon USING (true) WITH CHECK (true);
